- name: Install Gitlab
  hosts: gitlab
  become: yes

  tasks:
    - name: Docker pull gitlab image
      raw: docker pull gitlab/gitlab-ce:latest

    - name: Install gitlab
      raw: docker run --detach --hostname gitlab.example.com --publish 443:443 --publish 80:80 --name gitlab --restart always --volume /srv/gitlab/config:/etc/gitlab --volume /srv/gitlab/logs:/var/log/gitlab --volume /srv/gitlab/data:/var/opt/gitlab gitlab/gitlab-ce:latest
